spring.application.name=soul
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Força o Hibernate a criar/atualizar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Ative o console do H2 no navegador para você inspecionar o banco
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
