spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Dialeto do Hibernate para MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Cria/Atualiza as tabelas no MySQL automaticamente com base nas suas entidades JPA
spring.jpa.hibernate.ddl-auto=update

# Mostra as queries SQL no console (útil para debug)
spring.jpa.show-sql=true

# Configuração SMTP (Exemplo com Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
api.security.token.secret=${JWT_SECRET}